---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
    exclude_paths:
      # - logstash-core/lib
      # - logstash-core/spec
      # - "logstash-core-event/spec/logstash/event_spec.rb"
  fixme:
    enabled: false
  rubocop:
    enabled: false
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- logstash-core/lib
- logstash-core/spec
# - spec/
# - test/
# - lib/
